### ISSUE TITLE
video support?

### ISSUE THREAD

**Issue by jadedgnome** [rkouye/es-clip-image-search#1]
could this be used to support searching video frames?

**Comment by rkouye** [comment]
Sorry for the late reply, I had notification off.

You could detect "scene changing frames" (https://stackoverflow.com/questions/35675529/using-ffmpeg-how-to-do-a-scene-change-detection-with-timecode) then you embed theses frames just like standard images. Depending on your videos contents and storage resources you can play around with the sampling rate.
